swagger: '2.0'
info:
  title: Terraform Registry Service API
  version: '1.1.0'
  description: terraform registry service apis
paths:
  /healthz:
    get:
      operationId: getHealthz
      responses:
        '200':
          description: 'OK'
      summary: Health
  /:
    get:
      operationId: getHealth
      responses:
        '200':
          description: 'OK'
      summary: Health
  /providers:
    get:
      operationId: getProviders
      summary: get providers
      security:
        - Bearer: [ ]
      parameters:
        - type: integer
          name: page
          in: query
          required: true
          description: page number
        - type: integer
          name: pagesize
          in: query
          required: true
          description: no of records in each page
      responses:
        '200':
          description: Retreived
          schema:
            type: array
            items:
              $ref: '#/definitions/Provider'
        '400':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /providers/{provider_id}:
    get:
      operationId: getProviderById
      summary: get provider by ID
      security:
        - Bearer: [ ]
      parameters:
        - in: path
          name: provider_id
          type: string
          required: true
          description: 'provider id'
      responses:
        '200':
          description: Retreived
          schema:
            $ref: '#/definitions/Provider'
        '400':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /providers/{provider_id}/releases:
    get:
      operationId: getReleasesByProviderId
      summary: get releases by provider ID
      security:
        - Bearer: [ ]
      parameters:
        - in: path
          name: provider_id
          type: string
          required: true
          description: 'provider id'
      responses:
        '200':
          description: Retreived
          schema:
            type: array
            items:
              $ref: '#/definitions/Release'
        '400':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /releases/{provider_id}/{release_id}:
    get:
      operationId: getReleaseById
      summary: get release by ID
      security:
        - Bearer: [ ]
      parameters:
        - in: path
          name: provider_id
          type: string
          required: true
          description: 'provider id'
        - in: path
          name: release_id
          type: string
          required: true
          description: 'release id'
      responses:
        '200':
          description: Retreived
          schema:
            $ref: '#/definitions/Release'
        '400':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /releases/{provider_id}/{release_id}/attributes:
    get:
      operationId: getAttributesByReleaseId
      summary: get attributes of release by ID
      security:
        - Bearer: [ ]
      parameters:
        - in: path
          name: provider_id
          type: string
          required: true
          description: 'provider id'
        - in: path
          name: release_id
          type: string
          required: true
          description: 'release id'
      responses:
        '200':
          description: Retreived
          schema:
            type: array
            items:
              $ref: '#/definitions/Attribute'
        '400':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /releases/{provider_id}/{release_id}/{attribute_id}/details:
    get:
      operationId: getAttributeDetailsByAttributeId
      summary: get attributes details
      security:
        - Bearer: [ ]
      parameters:
        - in: path
          name: provider_id
          type: string
          required: true
          description: 'provider id'
        - in: path
          name: release_id
          type: string
          required: true
          description: 'release id'
        - in: path
          name: attribute_id
          type: string
          required: true
          description: 'release id'
      responses:
        '200':
          description: Retreived
          schema:
            $ref: '#/definitions/AttributeDetail'
        '400':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /resources/{provider_id}/{release_id}:
    get:
      operationId: getResourceSchemasByReleaseId
      summary: get resource schemas
      security:
        - Bearer: [ ]
      parameters:
        - in: path
          name: provider_id
          type: string
          required: true
          description: 'provider id'
        - in: path
          name: release_id
          type: string
          required: true
          description: 'release id'
      responses:
        '200':
          description: Retreived
          schema:
            type: array
            items:
              $ref: '#/definitions/ResourceSchema'
        '400':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /resources/{provider_id}/{release_id}/{resource_id}:
    get:
      operationId: getResourceSchemaAttributesById
      summary: get resource schema attributes
      security:
        - Bearer: [ ]
      parameters:
        - in: path
          name: provider_id
          type: string
          required: true
          description: 'provider id'
        - in: path
          name: release_id
          type: string
          required: true
          description: 'release id'
        - in: path
          name: resource_id
          type: string
          required: true
          description: 'resource id'
      responses:
        '200':
          description: Retreived
          schema:
            type: array
            items:
              $ref: '#/definitions/Attribute'
        '400':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /resources/{provider_id}/{release_id}/{resource_id}/{attribute_id}:
    get:
      operationId: getResourceSchemaAttributeById
      summary: get resource schema attributes
      security:
        - Bearer: [ ]
      parameters:
        - in: path
          name: provider_id
          type: string
          required: true
          description: 'provider id'
        - in: path
          name: release_id
          type: string
          required: true
          description: 'release id'
        - in: path
          name: resource_id
          type: string
          required: true
          description: 'resource id'
        - in: path
          name: attribute_id
          type: string
          required: true
          description: 'attribute id'
      responses:
        '200':
          description: Retreived
          schema:
            $ref: '#/definitions/AttributeDetail'
        '400':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /datasources/{provider_id}/{release_id}:
    get:
      operationId: getDataSourceSchemasByReleaseId
      summary: get data source schemas
      security:
        - Bearer: [ ]
      parameters:
        - in: path
          name: provider_id
          type: string
          required: true
          description: 'provider id'
        - in: path
          name: release_id
          type: string
          required: true
          description: 'release id'
      responses:
        '200':
          description: Retreived
          schema:
            type: array
            items:
              $ref: '#/definitions/DataSourceSchema'
        '400':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /datasources/{provider_id}/{release_id}/{datasource_id}:
    get:
      operationId: getDataSourceSchemasAttributesById
      summary: get data source schema attributes
      security:
        - Bearer: [ ]
      parameters:
        - in: path
          name: provider_id
          type: string
          required: true
          description: 'provider id'
        - in: path
          name: release_id
          type: string
          required: true
          description: 'release id'
        - in: path
          name: datasource_id
          type: string
          required: true
          description: 'datasource id'
      responses:
        '200':
          description: Retreived
          schema:
            type: array
            items:
              $ref: '#/definitions/Attribute'
        '400':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /datasources/{provider_id}/{release_id}/{datasource_id}/{attribute_id}:
    get:
      operationId: getDataSourceSchemaAttributeById
      summary: get data source schema attributes
      security:
        - Bearer: [ ]
      parameters:
        - in: path
          name: provider_id
          type: string
          required: true
          description: 'provider id'
        - in: path
          name: release_id
          type: string
          required: true
          description: 'release id'
        - in: path
          name: datasource_id
          type: string
          required: true
          description: 'datasource id'
        - in: path
          name: attribute_id
          type: string
          required: true
          description: 'attribute id'
      responses:
        '200':
          description: Retreived
          schema:
            $ref: '#/definitions/AttributeDetail'
        '400':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  Provider:
    title: Provider
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      full_name:
        type: string
      description:
        type: string
      logo_url:
        type: string
      source:
        type: string
      alias:
        type: string
  Release:
    title: Release
    type: object
    properties:
      id:
        type: string
      tag_name:
        type: string
      avatar_url:
        type: string
      published_at:
        type: string
  Attribute:
    title: Attribute
    type: string
  ResourceSchema:
    title: ResourceSchema
    type: string
  DataSourceSchema:
    title: DataSourceSchema
    type: string
  AttributeDetail:
    description: a attribute map[string] interface{}.
    type: object
    additionalProperties:
      type: object
  Message:
    type: object
    title: message
    properties:
      message:
        type: string
  ErrorResponse:
    type: object
    title: ErrorResponse
    properties:
      error:
        type: string
      description:
        type: string
securityDefinitions:
  Bearer:
    type: apiKey
    in: header
    name: Authorization
    description: JWT Token
consumes:
  - application/json
  - multipart/form-data
produces:
  - application/json
schemes:
  - https
x-google-backend:
  address: 'https://registry-api-dnkvna7iga-uc.a.run.app'
