{{- if .Values.argocdLocal.ingressIstio.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-server
  namespace: istio-system
{{- if .Values.argocdLocal.ingressIstio.annotations }}
  annotations:
{{ toYaml .Values.argocdLocal.ingressIstio.annotations | indent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ index .Values.argocdLocal.ingressIstio.hosts 0 }}
    http: 
      paths:
      - backend:
          serviceName: istio-ingressgateway-iap
          servicePort: 80
        path: /*
        pathType: ImplementationSpecific
{{ end }}