{{- if .Values.argocdLocal.virtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-server
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "{{ index .Values.argocdLocal.ingressIstio.hosts 0 }}"
  gateways:
  - {{ .Release.Namespace }}/argocd-server
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        port:
          number: 80
        host: {{ .Release.Name }}-argocd-server
{{ end }}